# semantic-release configuration file: https://semantic-release.gitbook.io/semantic-release/usage/configuration
# Used by the release workflow: .github/workflows/release.yml
preset: conventionalcommits
branches:
  - main
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"