sonar.projectKey=Alliander_sundael
sonar.organization=digitalisering

# Path to sources
sonar.sources=src/
sonar.test.inclusions=tests/** 

# Python
sonar.python.version=3
sonar.python.coverage.reportPaths=coverage.xml