name: ospo-code-check

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  code-check:
    uses: Alliander/ospo-workflows/.github/workflows/code-check.yml@main
    secrets: inherit
